title: Improve Accuracy via Network Dissection
description: By having understanding of units in network, we improved accrucay of network with controlling neruons.
theme: just-the-docs

url: https://taehyung.github.io/Improve-Accuracy-via-Netdissect

aux_links:
  Template Repository: https://github.com/taehyung/Improve-Accuracy-via-Netdissect
  
