title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://taehyung.github.io/Improve-Accuracy-via-Netdissect

aux_links:
  Template Repository: https://github.com/taehyung/Improve-Accuracy-via-Netdissect
  
